project_id = "cawajorzzgvhtjmfyvuv"

[functions.spotify-auth]
verify_jwt = false

[functions.spotify-data]
verify_jwt = false

[functions.spotify-top50]
verify_jwt = false

[functions.spotify-genre]
verify_jwt = false

[functions.create-playlist]
verify_jwt = false
